definitions:
  health_check.StatusCheck:
    properties:
      db_status:
        example: OK/ERROR
        type: string
    type: object
  response.DefaultResponse:
    properties:
      data: {}
      error_code:
        type: string
      message:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: rachmat.adi.p@gmail.com
    name: Rachmat Adi Prakoso
  description: This is boilerplate code for golang project
  title: Go-Boilerplate
  version: 1.0.0
paths:
  /health:
    get:
      description: API for do health check to dependencies used
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.DefaultResponse'
            - properties:
                data:
                  $ref: '#/definitions/health_check.StatusCheck'
              type: object
        "503":
          description: Service Unavailable
          schema:
            allOf:
            - $ref: '#/definitions/response.DefaultResponse'
            - properties:
                data:
                  $ref: '#/definitions/health_check.StatusCheck'
              type: object
      summary: Health Check
swagger: "2.0"
